
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/msys64/ucrt64/share/cmake/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/msys64/ucrt64/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/msys64/ucrt64/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/msys64/ucrt64/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Version MSBuild 17.14.14+a129329f1 pour .NET Framework
      La génération a démarré 16/12/2025 13:52:51.
      
      Projet "C:\\Users\\enola\\OneDrive\\Desktop\\Githubplateforme\\2026\\CPP\\2048-tile-twister\\build-vs\\CMakeFiles\\3.31.5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" sur le nœud 1 (cibles par défaut).
      PrepareForBuild:
        Création du répertoire "Debug\\".
        La sortie structurée est activée. La mise en forme du compilateur diagnostics reflète la hiérarchie des erreurs. Pour plus d’informations, consultez https://aka.ms/cpp/structured-output.
        Création du répertoire "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Création de "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
        Mise à jour de l'horodatage "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\enola\\OneDrive\\Desktop\\Githubplateforme\\2026\\CPP\\2048-tile-twister\\build-vs\\CMakeFiles\\3.31.5\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Suppression du fichier "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Mise à jour de l'horodatage "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Génération du projet "C:\\Users\\enola\\OneDrive\\Desktop\\Githubplateforme\\2026\\CPP\\2048-tile-twister\\build-vs\\CMakeFiles\\3.31.5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" terminée (cibles par défaut).
      
      La génération a réussi.
          0 Avertissement(s)
          0 Erreur(s)
      
      Temps écoulé 00:00:02.82
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/enola/OneDrive/Desktop/Githubplateforme/2026/CPP/2048-tile-twister/build-vs/CMakeFiles/3.31.5/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/msys64/ucrt64/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/msys64/ucrt64/share/cmake/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/enola/OneDrive/Desktop/Githubplateforme/2026/CPP/2048-tile-twister/build-vs/CMakeFiles/CMakeScratch/TryCompile-4td03m"
      binary: "C:/Users/enola/OneDrive/Desktop/Githubplateforme/2026/CPP/2048-tile-twister/build-vs/CMakeFiles/CMakeScratch/TryCompile-4td03m"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/enola/OneDrive/Desktop/Githubplateforme/2026/CPP/2048-tile-twister/build-vs/CMakeFiles/CMakeScratch/TryCompile-4td03m'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_c3658.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Version MSBuild 17.14.14+a129329f1 pour .NET Framework
        La génération a démarré 16/12/2025 13:52:55.
        
        Projet "C:\\Users\\enola\\OneDrive\\Desktop\\Githubplateforme\\2026\\CPP\\2048-tile-twister\\build-vs\\CMakeFiles\\CMakeScratch\\TryCompile-4td03m\\cmTC_c3658.vcxproj" sur le nœud 1 (cibles par défaut).
        PrepareForBuild:
          Création du répertoire "cmTC_c3658.dir\\Debug\\".
          La sortie structurée est activée. La mise en forme du compilateur diagnostics reflète la hiérarchie des erreurs. Pour plus d’informations, consultez https://aka.ms/cpp/structured-output.
          Création du répertoire "C:\\Users\\enola\\OneDrive\\Desktop\\Githubplateforme\\2026\\CPP\\2048-tile-twister\\build-vs\\CMakeFiles\\CMakeScratch\\TryCompile-4td03m\\Debug\\".
          Création du répertoire "cmTC_c3658.dir\\Debug\\cmTC_c3658.tlog\\".
        InitializeBuildStatus:
          Création de "cmTC_c3658.dir\\Debug\\cmTC_c3658.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
          Mise à jour de l'horodatage "cmTC_c3658.dir\\Debug\\cmTC_c3658.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_c3658.dir\\Debug\\\\" /Fd"cmTC_c3658.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue C:\\msys64\\ucrt64\\share\\cmake\\Modules\\CMakeCXXCompilerABI.cpp
          Compilateur d'optimisation Microsoft (R) C/C++ version 19.44.35211 pour x64
          Copyright (C) Microsoft Corporation. Tous droits réservés.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_c3658.dir\\Debug\\\\" /Fd"cmTC_c3658.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue C:\\msys64\\ucrt64\\share\\cmake\\Modules\\CMakeCXXCompilerABI.cpp
          CMakeCXXCompilerABI.cpp
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\enola\\OneDrive\\Desktop\\Githubplateforme\\2026\\CPP\\2048-tile-twister\\build-vs\\CMakeFiles\\CMakeScratch\\TryCompile-4td03m\\Debug\\cmTC_c3658.exe" /INCREMENTAL /ILK:"cmTC_c3658.dir\\Debug\\cmTC_c3658.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/enola/OneDrive/Desktop/Githubplateforme/2026/CPP/2048-tile-twister/build-vs/CMakeFiles/CMakeScratch/TryCompile-4td03m/Debug/cmTC_c3658.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/enola/OneDrive/Desktop/Githubplateforme/2026/CPP/2048-tile-twister/build-vs/CMakeFiles/CMakeScratch/TryCompile-4td03m/Debug/cmTC_c3658.lib" /MACHINE:X64  /machine:x64 cmTC_c3658.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_c3658.vcxproj -> C:\\Users\\enola\\OneDrive\\Desktop\\Githubplateforme\\2026\\CPP\\2048-tile-twister\\build-vs\\CMakeFiles\\CMakeScratch\\TryCompile-4td03m\\Debug\\cmTC_c3658.exe
        FinalizeBuildStatus:
          Suppression du fichier "cmTC_c3658.dir\\Debug\\cmTC_c3658.tlog\\unsuccessfulbuild".
          Mise à jour de l'horodatage "cmTC_c3658.dir\\Debug\\cmTC_c3658.tlog\\cmTC_c3658.lastbuildstate".
        Génération du projet "C:\\Users\\enola\\OneDrive\\Desktop\\Githubplateforme\\2026\\CPP\\2048-tile-twister\\build-vs\\CMakeFiles\\CMakeScratch\\TryCompile-4td03m\\cmTC_c3658.vcxproj" terminée (cibles par défaut).
        
        La génération a réussi.
            0 Avertissement(s)
            0 Erreur(s)
        
        Temps écoulé 00:00:02.94
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/msys64/ucrt64/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "C:/msys64/ucrt64/share/cmake/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/msys64/ucrt64/share/cmake/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/msys64/ucrt64/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:255 (cmake_determine_linker_id)"
      - "C:/msys64/ucrt64/share/cmake/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the CXX compiler's linker: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.44.35211.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
